name: notustohtml
description: Convert the Notus document format to an HTML representation.
version: 0.0.6
homepage: https://github.com/JacobWrenn/notustohtml

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  notus:
    # path: '../zefyr/packages/notus'
    git:
      url: git://github.com/organicinternet/zefyr.git
      path: packages/notus/
      ref: master
  quill_delta: ^1.0.0
  html: ^0.14.0

dev_dependencies:
  test:

publish_to: none
